INSERT INTO WALLET (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SURNAME,CUSTOMER_BALANCE) VALUES (1,'Oguzhan','Demirer',1000);
INSERT INTO WALLET (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SURNAME,CUSTOMER_BALANCE) VALUES (2,'John','Doe',1000);
INSERT INTO WALLET (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SURNAME,CUSTOMER_BALANCE) VALUES (3,'Leeroy','Jenkins',1000);
INSERT INTO WALLET (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_SURNAME,CUSTOMER_BALANCE) VALUES (4,'Lilly','Smith',1000);

INSERT INTO TRANSACTION (TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_TYPE,TRANSACTION_AMOUNT,TRANSACTION_DATE) VALUES (1,1,'Credit Operation',1000, CURRENT_TIMESTAMP());
INSERT INTO TRANSACTION (TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_TYPE,TRANSACTION_AMOUNT,TRANSACTION_DATE) VALUES (2,2,'Credit Operation',1000, CURRENT_TIMESTAMP());
INSERT INTO TRANSACTION (TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_TYPE,TRANSACTION_AMOUNT,TRANSACTION_DATE) VALUES (3,3,'Credit Operation',1000, CURRENT_TIMESTAMP());
INSERT INTO TRANSACTION (TRANSACTION_ID,CUSTOMER_ID,TRANSACTION_TYPE,TRANSACTION_AMOUNT,TRANSACTION_DATE) VALUES (4,4,'Credit Operation',1000, CURRENT_TIMESTAMP());

